### ISSUE TITLE
Compatibility with PSX Disc Combining Kits

### ISSUE THREAD

**Issue by wad11656** [NRGDEAD/Cue2cu2#4]
I tried creating a PSP PSX EBOOT file of a combined (Disc1 + Disc2) Brain Dead 13 image using [this tool](https://www.ps2-home.com/forum/viewtopic.php?t=104) through `pop-fe-psp.exe`, which can be found [here](https://github.com/sahlberg/pop-fe). But I got the following error:

![image](https://github.com/NRGDEAD/Cue2cu2/assets/16929664/fb380485-4b87-45f9-8d5a-a7a89bb34f24)

Since it looks like the issue is with the cue2cu2 process, I opened the issue on your github page instead of `pop-fe`. Do you think you could try making your code compatible with the combined psx disc kits above, and thus theoretically compatible with `pop-fe`? Thank you

**Comment by NRGDEAD** [comment]
Hmm. Cue2cu2 is really just intended to convert cue sheets to CU2, and I'm not very familiar with the programs you linked.
But since there are obviously cue sheets involved at some point, can you provide both of them for this game? Then I can have a look. No guarantees, though. ;-)

**Comment by wad11656** [comment]
The (unofficially) combined .cue is actually small:
```
FILE "braindead13.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```

It's okay--I knew it was a long-shot. Thank you for your response
